// Generates ORIGINAL decorative line art (stand-ins) inside the original viewBoxes so scroll-driven
// drawing (which depends on the path's bounding box) behaves identically.
// Output: src/components/decor/paths.ts        Usage: node tools/standins/lines.mjs
import fs from 'node:fs';

/** Catmull-Rom spline through points → cubic Bézier path data. */
function spline(pts, tension = 1) {
  let d = `M ${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i - 1] || pts[i], p1 = pts[i], p2 = pts[i + 1], p3 = pts[i + 2] || p2;
    const c1 = [p1[0] + ((p2[0] - p0[0]) / 6) * tension, p1[1] + ((p2[1] - p0[1]) / 6) * tension];
    const c2 = [p2[0] - ((p3[0] - p1[0]) / 6) * tension, p2[1] - ((p3[1] - p1[1]) / 6) * tension];
    d += ` C ${c1.map((v) => v.toFixed(1)).join(' ')} ${c2.map((v) => v.toFixed(1)).join(' ')} ${p2.map((v) => v.toFixed(1)).join(' ')}`;
  }
  return d;
}
function polyLength(pts) { let L = 0; for (let i = 1; i < pts.length; i++) L += Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]); return L; }

// Hero: two long sweeping loops, 780×1140 viewBox, bbox ≈ x 88–743, y 0–1140 (original bboxes)
// Loop is drawn in the first ~40 % of the length (visible at load, like the original's weight), then
// the line trails down-left and exits at the bottom. bbox ≈ x 88–743, y 0–1140.
const heroA = [[520, 700], [390, 590], [300, 440], [320, 270], [450, 120], [620, 30], [743, 0], [700, 70], [570, 210], [400, 390], [240, 570], [120, 740], [88, 880], [150, 1000], [310, 1070], [470, 1140]];
const heroB = [[545, 690], [410, 580], [318, 430], [338, 262], [466, 116], [630, 32], [730, 8], [684, 80], [552, 222], [384, 404], [226, 586], [110, 756], [96, 890], [168, 1006], [330, 1074], [490, 1140]];

// Waves: gentle meander across 6000×680 (horizontal), bbox spans full width, height ≈ 40–640
function meander(seed, amp, turns) {
  let s = seed; const rnd = () => ((s = (s * 16807) % 2147483647) / 2147483647);
  const pts = [];
  for (let i = 0; i <= turns; i++) { const x = (6000 * i) / turns; const y = 340 + Math.sin(i * 1.3 + seed) * amp * (0.6 + 0.4 * rnd()); pts.push([x, y]); }
  return pts;
}
const waveA = meander(7, 280, 26), waveB = meander(11, 250, 24);

const out = `// GENERATED by tools/standins/lines.mjs — original stand-in line art (not derived from the template).
export const PATHS = {
  heroA: { viewBox: '0 0 780 1140', d: ${JSON.stringify(spline(heroA))} },
  heroB: { viewBox: '0 0 780 1140', d: ${JSON.stringify(spline(heroB))} },
  waveA: { viewBox: '0 0 6000 680', d: ${JSON.stringify(spline(waveA))} },
  waveB: { viewBox: '0 0 6000 680', d: ${JSON.stringify(spline(waveB))} },
} as const;
export type PathName = keyof typeof PATHS;
`;
fs.writeFileSync(new URL('../../src/components/decor/paths.ts', import.meta.url), out);
console.log('approx lengths', Math.round(polyLength(heroA)), Math.round(polyLength(heroB)));
