/**
 * Stand-in photo registry (generated by tools/standins/generate.py; see public/standins/manifest.json).
 * Sizes are the ORIGINAL pixel sizes; `position` is the original object-position (ASSETS.md §1).
 */
const s = (slot: string, width: number, height: number, position = '50% 50%') =>
  ({ src: `/standins/${slot}.jpg`, width, height, position }) as const;

export const STANDINS = {
  'hero-backdrop': s('hero-backdrop', 2048, 2048, '49.5% 28.4%'),
  'hero-portrait': s('hero-portrait', 3600, 3200, '50% 0%'),
  'service-1': s('service-1', 2048, 2048),
  'service-2': s('service-2', 2048, 2048),
  'service-3': s('service-3', 2048, 2048),
  'service-4': s('service-4', 2048, 2048),
  'story-a-1': s('story-a-1', 2048, 2048),
  'story-a-2': s('story-a-2', 2048, 2048),
  'story-b-1': s('story-b-1', 2048, 2048),
  'story-b-2': s('story-b-2', 2048, 2048),
  'big-quote': s('big-quote', 2048, 2048),
  'journal-a': s('journal-a', 2048, 2048),
  'journal-b': s('journal-b', 2048, 2048),
  'journal-c': s('journal-c', 2048, 2048),
  footer: s('footer', 2048, 2048),
  'avatar-1': s('avatar-1', 280, 280),
  'avatar-2': s('avatar-2', 512, 512),
  'avatar-3': s('avatar-3', 512, 512),
  'avatar-4': s('avatar-4', 512, 512),
  'avatar-5': s('avatar-5', 512, 512),
} as const;

export type StandInSlot = keyof typeof STANDINS;

export const MASKS = {
  blobA: '/masks/blob-a.svg',
  blobB: '/masks/blob-b.svg',
  blobC: '/masks/blob-c.svg',
  avatarRing: '/masks/avatar-ring.svg',
} as const;

export const TEXTURES = { noiseA: '/textures/noise-a.png', noiseB: '/textures/noise-b.png' } as const;
